spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/foodexpress
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  servlet:
    context-path: /api

security:
  jwt:
    secret: your_jwt_secret_key_here
    expiration: 86400000 # 24 hours in milliseconds

cors:
  allowed-origins: http://localhost:3000

clerk:
  secret:
    key: your_clerk_secret_key_here

firebase:
  storage:
    bucket: ${REACT_APP_FIREBASE_STORAGE_BUCKET}
