server:
  port: 8081
  servlet:
    context-path: /

cors:
  allowed-origins: http://localhost:3000

clerk:
  secret:
    key: your_clerk_secret_key_here

firebase:
  storage:
    bucket: ${REACT_APP_FIREBASE_STORAGE_BUCKET}




